scheduler:./src/scheduler_interface.cpp
	g++ -c ./src/scheduler_interface.cpp
	g++ scheduler_interface.o -o scheduler

metrics:./src/bulk_metrics.cpp
	g++ -c ./src/bulk_metrics.cpp
	g++ bulk_metrics.o -o bulk_metrics

run:
	./scheduler
